### ISSUE TITLE
Adding swarmspawner to jupyterhub

### ISSUE THREAD

**Issue by mattwg** [compmodels/jupyterhub#2]
How do I include the swarmspawner?  Do I need to add files to dockerspawner and then run setup.py?

Can I also check that docker swarm manages to swarm independently of the swarmspawner / Jupyterhub.  In other words am I correct that I should I create the swarm before using the swarmspawner.

Matt

**Comment by jhamrick** [comment]
Yes, you need to get swarm up and running before you will be able to use the swarmspawner. Once you have it running, you just need to put `swarmspawner.py` in a place where JupyterHub can import it (e.g. in the directory where you run JupyterHub).

**Comment by jhamrick** [comment]
FYI, SwarmSpawner is no longer necessary -- DockerSpawner and SystemUserSpawner now work out-of-the-box with swarm.
