### ISSUE TITLE
DriverStatus vs SystemStatus

### ISSUE THREAD

**Issue by agrzywac** [compmodels/jupyterhub#4]
I have a swarm test setup on my Mac composed of two masters two nodes and a consul. The DriverStatus is always comming back with None.  This is a problem as node information is not populated. I have replaced it with SystemStatus reference but am strugling to find any rational documentation on either. Any comments, references would be welcome.
Adam

**Comment by jhamrick** [comment]
Hi Adam, you actually shouldn't need to use SwarmSpawner anymore to get swarm working -- you should be able to use just DockerSpawner (or SystemUserSpawner) and then probably this won't be an issue anymore. See https://github.com/jupyterhub/dockerspawner/pull/54#issuecomment-184873543 for an example Kyle gave of a working swarm setup with DockerSpawner.

**Comment by shreddd** [comment]
@jhamrick - can I suggest adding  jupyterhub/dockerspawner#54 to the readme?

**Comment by jhamrick** [comment]
I've now updated this image so that it should work with swarm without needing SwarmSpawner, and have made a PR on the DockerSpawner repo to document how to get it working with swarm.
